rumah:
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0

dapur:
  position:
    x: 2.15
    y: -1.32
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.71
    w: 0.70